import { Inter } from "next/font/google";
import "./globals.css";
import {DefaultSidebar} from "@/app/ui/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className="bg-gray-800">
                    <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
                        <div className="w-full flex-none md:w-64">
                            <DefaultSidebar />
                        </div>
                        <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
                    </div>
                    {children}
                </main>
            </body>
        </html>
    );
}
